"""GovEngine package-in-place seam for Ravenclaw extraction.

This package exposes neutral context, policy, runner, and safety-control
contracts without importing optional contract-lifecycle dependencies at package
import time.
"""

from typing import Any

__version__ = '0.16.12rc1'

from .admission import (
    AuditLedgerAppendResult,
    AuditLedgerEntry,
    AuditLedgerPort,
    AuditLedgerVerificationResult,
    GovAdmissionDecision,
    GovApprovalRequest,
    GovAuditRecord,
    GovPolicyDecision,
    JsonlAuditLedgerAdapter,
    RuntimeAdmissionResult,
    admission_decision_from_host_gate,
    audit_ledger_verification_public_summary,
    audit_ledger_entry_digest,
    audit_record_public_summary,
    compose_runtime_admission_result,
    normalize_admission_artifact_refs,
    policy_verdict_to_gov_policy_decision,
    runtime_admission_public_summary,
    validate_admission_decision,
    validate_approval_request,
    validate_audit_record,
    validate_audit_ledger_append_result,
    validate_audit_ledger_entry,
    validate_audit_ledger_verification_result,
    validate_policy_decision,
    validate_runtime_admission_result,
    validate_runtime_admission_proof_inputs,
)
from .api import GovApiError, GovApiResult
from .contract_compatibility import (
    CONTRACT_COMPATIBILITY_REQUEST_SCHEMA_VERSION,
    SUPPORTED_CONTRACT_REPORT_SCHEMA_VERSION,
    ContractCompatibilityReport,
    ContractCompatibilityRequest,
    contract_major_version,
    evaluate_contract_compatibility,
    supported_contract_report,
    validate_contract_compatibility_request,
    validate_supported_contract_version,
)
from .automation import (
    AUTOMATION_TRANSITION_REQUEST_SCHEMA_VERSION as AUTOMATION_TRANSITION_REQUEST_SCHEMA_VERSION,
    SUPPORTED_AUTOMATION_CHAIN_SCHEMA_REF as SUPPORTED_AUTOMATION_CHAIN_SCHEMA_REF,
    AutomationTransitionRequest as AutomationTransitionRequest,
    admit_automation_transition as admit_automation_transition,
    automation_transition_admission_digest as automation_transition_admission_digest,
    automation_transition_request_digest as automation_transition_request_digest,
    validate_automation_transition_admission as validate_automation_transition_admission,
    validate_automation_transition_request as validate_automation_transition_request,
)
from .automation_explain import (
    AUTOMATION_TRANSITION_EXPLANATION_SCHEMA_VERSION as AUTOMATION_TRANSITION_EXPLANATION_SCHEMA_VERSION,
    AutomationTransitionExplanation as AutomationTransitionExplanation,
    explain_automation_transition as explain_automation_transition,
)
from .governance_trace import (
    GOVERNANCE_TRACE_SCHEMA_VERSION,
    GovernanceTrace,
    policy_request_digest,
    project_governance_trace,
)
from .boundary import (
    BoundaryReport,
    DomainProfileConformance,
    DomainProfileContract,
    KernelBoundary,
    boundary_surface_index,
    domain_profile_conformance,
    kernel_boundary_contract,
    kernel_boundary_report,
    known_profile_contracts,
    ravenclaw_profile_contract,
    validate_domain_profile_contract,
    validate_domain_profile_conformance,
)
from .context import GovEngineContext, GovEnginePaths, host_compat_context, ravenclaw_context
from .control import ControlDecision, apply_control_decision, validate_control_decision
from .contract_proofs import (
    GovernanceVocabularyEntry,
    RuntimeContractProof,
    governance_contract_vocabulary,
    ravenclaw_contract_proof,
    tecrax_contract_proof,
    validate_governance_contract_vocabulary,
    validate_runtime_contract_proof,
)
from .core import (
    ArtifactDescriptor,
    ArtifactEnvelope,
    ArtifactState,
    ExecutionPrerequisites,
    GovernanceContext,
    ReasonCode,
    TransitionDecision,
)
from .deconfliction import ArtifactChangeOrder, ArtifactConflict, ConflictDetector
from .events import EventEnvelope, GovEvent, validate_event_envelope, validate_gov_event
from .execution.gate import DryRunRunner, ExecutionGate, ExecutionGateInput, RunnerProfile
from .execution.runner_protocol import runner_receipt_public_summary
from .execution.supervision import (
    GovRunnerLease,
    GovSupervisionDecision,
    GovSupervisionPlan,
    LocalSubprocessRunnerReadiness,
    evaluate_local_subprocess_runner_readiness,
    runner_lease_from_request,
    supervision_plan_from_runner_request,
    validate_runner_lease,
    validate_runner_receipt_binding,
    validate_runner_receipt_for_request,
    validate_supervised_runner_request,
    validate_supervision_decision,
    validate_supervision_plan,
)
from .execution_backend import CommandResult, GovExecutionBackend
from .lifecycle import ArtifactLifecycleController, TransitionGate, TransitionPolicy, canonical_lifecycle_state
from .ooda import GovObservation, GovOodaController, GovOodaDecision, GovOrientation
from .orchestration import (
    OrchestrationStep,
    OrchestratorBoundary,
    orchestrator_boundary_contract,
    validate_orchestration_step,
)
from .planning import (
    GovPlanIntentContract,
    GovTaskContract,
    PlannerPort,
    task_contract_from_host_task,
    validate_plan_intent_contract,
    validate_planner_port,
    validate_task_contract,
)
from .policy import (
    CompiledPolicyPack,
    CompileResult,
    PolicyCompiler,
    PolicyConstraint,
    PolicyEngine,
    PolicyEnforcementPlan,
    PolicyEvaluationExplanation,
    PolicyObligation,
    PolicyRequest,
    PolicyRule,
    PolicyVerdict,
    RuntimeControlProjection,
    admit_policy_execution,
    compile_policy_pack,
    evaluate_policy,
    explain_policy_evaluation,
    policy_enforcement_admission,
    policy_enforcement_admission_digest,
    policy_enforcement_plan_digest,
    policy_pack_digest,
    policy_verdict_digest,
    project_runtime_controls,
    validate_policy_enforcement_admission,
    validate_policy_enforcement_plan,
    validate_policy_request,
    validate_policy_verdict,
)
from .profiles import (
    CapabilityDeclaration,
    DomainProfile,
    EvidenceRuleDeclaration,
    PlanningStageRegistry,
    PolicyHookDeclaration,
    ProfileConformanceReport,
    ResourceTypeRegistry,
    RunnerProfileDeclaration,
    TaskFamilyRegistry,
    profile_conformance_report,
    ravenclaw_security_profile,
    tecrax_infra_ops_profile,
    validate_domain_profile,
    validate_profile_conformance,
)
from .roles import GovRoleAdapters
from .review import (
    GovEvidenceClaim,
    GovEvidenceQualification,
    GovEvidenceRequirement,
    GovReviewResult,
    evidence_claim_public_summary,
    qualify_evidence_claim,
    review_result_public_summary,
    validate_evidence_review_chain,
    validate_evidence_claim,
    validate_evidence_qualification,
    validate_evidence_requirement,
    validate_review_result,
)
from .replay import (
    GuardedBundleRuntimeDecision,
    GuardReplayDecision,
    GuardReplayRecord,
    InMemoryReplayClaimStore,
    ReplayClaimStore,
    evaluate_guard_replay,
    guard_replay_record_from_guard,
    record_guard_replay,
    record_guard_replay_file,
    verify_guard_and_record_replay,
)
from .runtime_shell import (
    GovControlAction,
    GovQueueLane,
    GovQueueSnapshot,
    GovRuntimeSnapshot,
    GovSchedulerTick,
    control_action_from_host_action,
    queue_snapshot_from_lanes,
    validate_control_action,
    validate_queue_snapshot,
    validate_runtime_snapshot,
    validate_scheduler_tick,
)
from .scope_ports import FunctionalScopePort, GovScopePort
from .triggers import (
    TRIGGER_PLANNING_REQUEST_SCHEMA_VERSION,
    TriggerPlanningRequest,
    admit_trigger_planning,
    trigger_planning_admission_digest,
    trigger_planning_request_digest,
    validate_trigger_planning_admission,
    validate_trigger_planning_request,
)
from .supervisor_actions import (
    SUPERVISOR_ACTION_REQUEST_SCHEMA_VERSION,
    SupervisorActionRequest,
    admit_supervisor_action,
    supervisor_action_admission_digest,
    supervisor_action_request_digest,
    validate_supervisor_action_admission,
    validate_supervisor_action_request,
)
from .supervisor_explain import (
    SUPERVISOR_EXPLANATION_SCHEMA_VERSION,
    SupervisorActionExplanation,
    explain_supervisor_action,
)
from .profile_governance import (
    PROFILE_CONNECTOR_COMPATIBILITY_SCHEMA_VERSION,
    PROFILE_GOVERNANCE_PROJECTION_SCHEMA_VERSION,
    PROFILE_GOVERNANCE_REQUEST_SCHEMA_VERSION,
    ProfileConnectorCompatibilityReport,
    ProfileGovernanceBundle,
    ProfileGovernanceProjection,
    ProfileGovernanceRequest,
    evaluate_profile_connector_compatibility,
    explain_profile_governance,
    profile_governance_request_digest,
    project_profile_governance,
    validate_profile_governance_request,
)
from .typed_execution_governance import (
    RUNTIME_CAPABILITY_DESCRIPTOR_SCHEMA_VERSION,
    TYPED_EXECUTION_CAPABILITY_COMPATIBILITY_SCHEMA_VERSION,
    TYPED_EXECUTION_CONTROL_CATALOG_SCHEMA_VERSION,
    TYPED_EXECUTION_GOVERNANCE_PROJECTION_SCHEMA_VERSION,
    TYPED_EXECUTION_GOVERNANCE_REQUEST_SCHEMA_VERSION,
    TYPED_EXECUTION_STACK_COMPATIBILITY_SCHEMA_VERSION,
    RuntimeCapabilityDescriptor,
    TypedExecutionCapabilityCompatibilityReport,
    TypedExecutionGovernanceBundle,
    TypedExecutionGovernanceProjection,
    TypedExecutionGovernanceRequest,
    TypedExecutionStackCompatibilityReport,
    TypedExecutionStackCompatibilityRequest,
    admit_typed_execution,
    evaluate_typed_execution_capability_compatibility,
    evaluate_typed_execution_stack_compatibility,
    explain_typed_execution_governance,
    map_policy_verdict_to_typed_execution_controls,
    project_typed_execution_governance,
    project_typed_execution_policy_overlay,
    typed_execution_admission_digest,
    typed_execution_control_catalog,
    typed_execution_governance_request_digest,
    validate_runtime_capability_descriptor,
    validate_typed_execution_admission,
    validate_typed_execution_governance_request,
    validate_typed_execution_stack_compatibility_request,
)
from .signing import (
    DemoDigestSigner,
    DemoDigestVerifier,
    KeyResolutionRequest,
    KeyResolutionResult,
    KeyResolverPort,
    SignatureEnvelope,
    SignedArtifact,
    SigningPolicy,
    TrustPolicy,
    TrustStoreDecision,
    TrustStorePort,
    VerificationResult,
    canonical_govengine_record,
    demo_sign_and_verify,
    demo_sign_govengine_record,
    govengine_record_digest,
    signed_artifact_from_record,
    signature_transition_decision,
    verify_signed_govengine_record,
)
from .state_index import ArtifactStateIndex
from .state_machine import (
    GovRunState,
    StateTransition,
    apply_state_transition,
    validate_run_state,
    validate_state_transition,
)
from .state_store import GovStateStore
from .surfaces import (
    GovSurface,
    admission_policy_surface,
    domain_profile_sdk_surface,
    public_surface_index,
    runtime_contract_proofs_surface,
)

__all__ = [
    'AuditLedgerAppendResult',
    'AuditLedgerEntry',
    'AuditLedgerPort',
    'AuditLedgerVerificationResult',
    'CapabilityDeclaration',
    'CommandResult',
    'CompiledPolicyPack',
    'CONTRACT_COMPATIBILITY_REQUEST_SCHEMA_VERSION',
    'CompileResult',
    'ContractCompatibilityReport',
    'ContractCompatibilityRequest',
    'BoundaryReport',
    'ControlDecision',
    'DomainProfile',
    'DomainProfileConformance',
    'DomainProfileContract',
    'EvidenceRuleDeclaration',
    'GovAdmissionDecision',
    'GovApiError',
    'GovApiResult',
    'GovApprovalRequest',
    'GovAuditRecord',
    'JsonlAuditLedgerAdapter',
    'GovEngineContext',
    'GovEnginePaths',
    'GovEvidenceClaim',
    'GovEvidenceQualification',
    'GovEvidenceRequirement',
    'GovControlAction',
    'GovernanceVocabularyEntry',
    'ArtifactChangeOrder',
    'ArtifactConflict',
    'ArtifactDescriptor',
    'ArtifactEnvelope',
    'ArtifactLifecycleController',
    'ArtifactState',
    'ArtifactStateIndex',
    'ConflictDetector',
    'ExecutionGate',
    'ExecutionGateInput',
    'ExecutionPrerequisites',
    'EventEnvelope',
    'DryRunRunner',
    'DemoDigestSigner',
    'DemoDigestVerifier',
    'GovernanceContext',
    'GovExecutionBackend',
    'GovEvent',
    'GovObservation',
    'GovOodaController',
    'GovOodaDecision',
    'GovOrientation',
    'GovPlanIntentContract',
    'GovPolicyDecision',
    'GovQueueLane',
    'GovQueueSnapshot',
    'GovReviewResult',
    'GovRoleAdapters',
    'GovRunnerLease',
    'GovRunState',
    'GovRuntimeSnapshot',
    'GovSchedulerTick',
    'RuntimeAdmissionResult',
    'GuardedBundleRuntimeDecision',
    'GuardReplayDecision',
    'GuardReplayRecord',
    'InMemoryReplayClaimStore',
    'ReplayClaimStore',
    'GovSurface',
    'GovSupervisionDecision',
    'GovSupervisionPlan',
    'GovTaskContract',
    'KernelBoundary',
    'KeyResolutionRequest',
    'KeyResolutionResult',
    'KeyResolverPort',
    'OrchestrationStep',
    'OrchestratorBoundary',
    'PlanningStageRegistry',
    'PlannerPort',
    'PolicyCompiler',
    'PolicyConstraint',
    'PolicyEngine',
    'PolicyEnforcementPlan',
    'PolicyEvaluationExplanation',
    'PolicyHookDeclaration',
    'PolicyObligation',
    'PolicyRequest',
    'PolicyRule',
    'PolicyVerdict',
    'RuntimeControlProjection',
    'ProfileConformanceReport',
    'LocalSubprocessRunnerReadiness',
    'ResourceTypeRegistry',
    'RuntimeContractProof',
    'RunnerProfileDeclaration',
    'TaskFamilyRegistry',
    'FunctionalScopePort',
    'ReasonCode',
    'RunnerProfile',
    'GovScopePort',
    'SignatureEnvelope',
    'SignedArtifact',
    'SigningPolicy',
    'StateTransition',
    'GovSCLiteLifecycleVerifier',
    'GovStateStore',
    'review_bundle_state',
    'review_bundle_transition_decision',
    'review_sclite_bundle',
    'review_result_public_summary',
    'TransitionDecision',
    'TransitionGate',
    'TransitionPolicy',
    'TRIGGER_PLANNING_REQUEST_SCHEMA_VERSION',
    'SUPERVISOR_ACTION_REQUEST_SCHEMA_VERSION',
    'AUTOMATION_TRANSITION_REQUEST_SCHEMA_VERSION',
    'AUTOMATION_TRANSITION_EXPLANATION_SCHEMA_VERSION',
    'SUPPORTED_AUTOMATION_CHAIN_SCHEMA_REF',
    'SUPPORTED_CONTRACT_REPORT_SCHEMA_VERSION',
    'SUPERVISOR_EXPLANATION_SCHEMA_VERSION',
    'TriggerPlanningRequest',
    'SupervisorActionRequest',
    'SupervisorActionExplanation',
    'AutomationTransitionRequest',
    'AutomationTransitionExplanation',
    'TrustPolicy',
    'TrustStoreDecision',
    'TrustStorePort',
    'VerificationResult',
    'admission_decision_from_host_gate',
    'admission_policy_surface',
    'admit_policy_execution',
    'admit_trigger_planning',
    'admit_supervisor_action',
    'admit_automation_transition',
    'explain_supervisor_action',
    'explain_automation_transition',
    'explain_profile_governance',
    'evaluate_profile_connector_compatibility',
    'PROFILE_CONNECTOR_COMPATIBILITY_SCHEMA_VERSION',
    'PROFILE_GOVERNANCE_PROJECTION_SCHEMA_VERSION',
    'PROFILE_GOVERNANCE_REQUEST_SCHEMA_VERSION',
    'ProfileConnectorCompatibilityReport',
    'ProfileGovernanceBundle',
    'ProfileGovernanceProjection',
    'ProfileGovernanceRequest',
    'profile_governance_request_digest',
    'project_profile_governance',
    'validate_profile_governance_request',
    'RUNTIME_CAPABILITY_DESCRIPTOR_SCHEMA_VERSION',
    'TYPED_EXECUTION_CAPABILITY_COMPATIBILITY_SCHEMA_VERSION',
    'TYPED_EXECUTION_CONTROL_CATALOG_SCHEMA_VERSION',
    'TYPED_EXECUTION_GOVERNANCE_PROJECTION_SCHEMA_VERSION',
    'TYPED_EXECUTION_GOVERNANCE_REQUEST_SCHEMA_VERSION',
    'TYPED_EXECUTION_STACK_COMPATIBILITY_SCHEMA_VERSION',
    'RuntimeCapabilityDescriptor',
    'TypedExecutionCapabilityCompatibilityReport',
    'TypedExecutionGovernanceBundle',
    'TypedExecutionGovernanceProjection',
    'TypedExecutionGovernanceRequest',
    'TypedExecutionStackCompatibilityReport',
    'TypedExecutionStackCompatibilityRequest',
    'admit_typed_execution',
    'evaluate_typed_execution_capability_compatibility',
    'evaluate_typed_execution_stack_compatibility',
    'explain_typed_execution_governance',
    'map_policy_verdict_to_typed_execution_controls',
    'project_typed_execution_governance',
    'project_typed_execution_policy_overlay',
    'typed_execution_admission_digest',
    'typed_execution_control_catalog',
    'typed_execution_governance_request_digest',
    'validate_runtime_capability_descriptor',
    'validate_typed_execution_admission',
    'validate_typed_execution_governance_request',
    'validate_typed_execution_stack_compatibility_request',
    'apply_control_decision',
    'audit_ledger_entry_digest',
    'audit_ledger_verification_public_summary',
    'audit_record_public_summary',
    'compile_policy_pack',
    'contract_major_version',
    'supported_contract_report',
    'validate_contract_compatibility_request',
    'validate_supported_contract_version',
    'compose_runtime_admission_result',
    'normalize_admission_artifact_refs',
    'control_action_from_host_action',
    'demo_sign_and_verify',
    'demo_sign_govengine_record',
    'apply_state_transition',
    'boundary_surface_index',
    'canonical_govengine_record',
    'canonical_lifecycle_state',
    'domain_profile_conformance',
    'domain_profile_sdk_surface',
    'evaluate_local_subprocess_runner_readiness',
    'evaluate_guard_replay',
    'evaluate_contract_compatibility',
    'evaluate_policy',
    'GOVERNANCE_TRACE_SCHEMA_VERSION',
    'GovernanceTrace',
    'explain_policy_evaluation',
    'evidence_claim_public_summary',
    'governance_contract_vocabulary',
    'guard_replay_record_from_guard',
    'govengine_record_digest',
    'host_compat_context',
    'kernel_boundary_contract',
    'kernel_boundary_report',
    'known_profile_contracts',
    'orchestrator_boundary_contract',
    'policy_verdict_to_gov_policy_decision',
    'policy_enforcement_admission',
    'policy_enforcement_admission_digest',
    'policy_enforcement_plan_digest',
    'policy_pack_digest',
    'policy_request_digest',
    'policy_verdict_digest',
    'project_governance_trace',
    'project_runtime_controls',
    'public_surface_index',
    'qualify_evidence_claim',
    'queue_snapshot_from_lanes',
    'ravenclaw_context',
    'ravenclaw_contract_proof',
    'ravenclaw_profile_contract',
    'ravenclaw_security_profile',
    'record_guard_replay',
    'record_guard_replay_file',
    'verify_guard_and_record_replay',
    'verify_signed_govengine_record',
    'runner_lease_from_request',
    'runner_receipt_public_summary',
    'runtime_admission_public_summary',
    'runtime_contract_proofs_surface',
    'signed_artifact_from_record',
    'signature_transition_decision',
    'supervision_plan_from_runner_request',
    'tecrax_contract_proof',
    'tecrax_infra_ops_profile',
    'trigger_planning_admission_digest',
    'trigger_planning_request_digest',
    'supervisor_action_admission_digest',
    'supervisor_action_request_digest',
    'automation_transition_admission_digest',
    'automation_transition_request_digest',
    'validate_admission_decision',
    'validate_approval_request',
    'validate_audit_record',
    'validate_audit_ledger_append_result',
    'validate_audit_ledger_entry',
    'validate_audit_ledger_verification_result',
    'validate_domain_profile',
    'validate_domain_profile_contract',
    'validate_domain_profile_conformance',
    'validate_control_decision',
    'validate_control_action',
    'validate_evidence_claim',
    'validate_evidence_qualification',
    'validate_evidence_requirement',
    'validate_evidence_review_chain',
    'validate_event_envelope',
    'validate_gov_event',
    'validate_governance_contract_vocabulary',
    'validate_orchestration_step',
    'task_contract_from_host_task',
    'validate_plan_intent_contract',
    'validate_planner_port',
    'validate_profile_conformance',
    'validate_policy_decision',
    'validate_policy_enforcement_admission',
    'validate_policy_enforcement_plan',
    'validate_policy_request',
    'validate_policy_verdict',
    'validate_queue_snapshot',
    'validate_runner_lease',
    'validate_runner_receipt_binding',
    'validate_runner_receipt_for_request',
    'validate_run_state',
    'validate_review_result',
    'validate_runtime_snapshot',
    'validate_runtime_contract_proof',
    'validate_scheduler_tick',
    'validate_runtime_admission_result',
    'validate_runtime_admission_proof_inputs',
    'validate_state_transition',
    'validate_supervised_runner_request',
    'validate_supervision_decision',
    'validate_supervision_plan',
    'validate_task_contract',
    'validate_trigger_planning_admission',
    'validate_trigger_planning_request',
    'validate_supervisor_action_admission',
    'validate_supervisor_action_request',
    'validate_automation_transition_admission',
    'validate_automation_transition_request',
    'verify_lifecycle_manifest',
    'profile_conformance_report',
]


def __getattr__(name: str) -> Any:
    if name in {
        'GovSCLiteLifecycleVerifier',
        'review_bundle_state',
        'review_bundle_transition_decision',
        'review_sclite_bundle',
        'verify_lifecycle_manifest',
    }:
        from .sclite_contracts import (
            GovSCLiteLifecycleVerifier,
            review_bundle_state,
            review_bundle_transition_decision,
            review_sclite_bundle,
            verify_lifecycle_manifest,
        )

        return {
            'GovSCLiteLifecycleVerifier': GovSCLiteLifecycleVerifier,
            'review_bundle_state': review_bundle_state,
            'review_bundle_transition_decision': review_bundle_transition_decision,
            'review_sclite_bundle': review_sclite_bundle,
            'verify_lifecycle_manifest': verify_lifecycle_manifest,
        }[name]
    raise AttributeError(name)
