"""GovEngine package-in-place seam for Ravenclaw extraction.

This package exposes neutral context, policy, runner, and safety-control
contracts without importing optional contract-lifecycle dependencies at package
import time.
"""

__version__ = '0.12.2a0'

from .admission import (
    GovAdmissionDecision,
    GovApprovalRequest,
    GovAuditRecord,
    GovPolicyDecision,
    RuntimeAdmissionResult,
    admission_decision_from_host_gate,
    compose_runtime_admission_result,
    validate_admission_decision,
    validate_approval_request,
    validate_audit_record,
    validate_policy_decision,
    validate_runtime_admission_result,
)
from .api import GovApiError, GovApiResult
from .boundary import (
    BoundaryReport,
    DomainProfileConformance,
    DomainProfileContract,
    KernelBoundary,
    boundary_surface_index,
    domain_profile_conformance,
    kernel_boundary_contract,
    kernel_boundary_report,
    known_profile_contracts,
    ravenclaw_profile_contract,
    validate_domain_profile_contract,
    validate_domain_profile_conformance,
)
from .context import GovEngineContext, GovEnginePaths, host_compat_context, ravenclaw_context
from .control import ControlDecision, apply_control_decision, validate_control_decision
from .contract_proofs import (
    GovernanceVocabularyEntry,
    RuntimeContractProof,
    governance_contract_vocabulary,
    ravenclaw_contract_proof,
    tecrax_contract_proof,
    validate_governance_contract_vocabulary,
    validate_runtime_contract_proof,
)
from .core import (
    ArtifactDescriptor,
    ArtifactEnvelope,
    ArtifactState,
    ExecutionPrerequisites,
    GovernanceContext,
    ReasonCode,
    TransitionDecision,
)
from .deconfliction import ArtifactChangeOrder, ArtifactConflict, ConflictDetector
from .events import EventEnvelope, GovEvent, validate_event_envelope, validate_gov_event
from .execution.gate import DryRunRunner, ExecutionGate, ExecutionGateInput, RunnerProfile
from .execution.supervision import (
    GovRunnerLease,
    GovSupervisionDecision,
    GovSupervisionPlan,
    runner_lease_from_request,
    supervision_plan_from_runner_request,
    validate_runner_lease,
    validate_runner_receipt_for_request,
    validate_supervised_runner_request,
    validate_supervision_decision,
    validate_supervision_plan,
)
from .execution_backend import CommandResult, GovExecutionBackend
from .lifecycle import ArtifactLifecycleController, TransitionGate, TransitionPolicy
from .ooda import GovObservation, GovOodaController, GovOodaDecision, GovOrientation
from .orchestration import (
    OrchestrationStep,
    OrchestratorBoundary,
    orchestrator_boundary_contract,
    validate_orchestration_step,
)
from .planning import (
    GovPlanIntentContract,
    GovTaskContract,
    PlannerPort,
    task_contract_from_host_task,
    validate_plan_intent_contract,
    validate_planner_port,
    validate_task_contract,
)
from .profiles import (
    CapabilityDeclaration,
    DomainProfile,
    EvidenceRuleDeclaration,
    PlanningStageRegistry,
    PolicyHookDeclaration,
    ProfileConformanceReport,
    ResourceTypeRegistry,
    RunnerProfileDeclaration,
    TaskFamilyRegistry,
    profile_conformance_report,
    ravenclaw_security_profile,
    tecrax_infra_ops_profile,
    validate_domain_profile,
    validate_profile_conformance,
)
from .roles import GovRoleAdapters
from .review import (
    GovEvidenceClaim,
    GovEvidenceQualification,
    GovEvidenceRequirement,
    GovReviewResult,
    qualify_evidence_claim,
    validate_evidence_claim,
    validate_evidence_qualification,
    validate_evidence_requirement,
    validate_review_result,
)
from .replay import (
    GuardedBundleRuntimeDecision,
    GuardReplayDecision,
    GuardReplayRecord,
    evaluate_guard_replay,
    guard_replay_record_from_guard,
    record_guard_replay,
    record_guard_replay_file,
    verify_guard_and_record_replay,
)
from .runtime_shell import (
    GovControlAction,
    GovQueueLane,
    GovQueueSnapshot,
    GovRuntimeSnapshot,
    GovSchedulerTick,
    control_action_from_host_action,
    queue_snapshot_from_lanes,
    validate_control_action,
    validate_queue_snapshot,
    validate_runtime_snapshot,
    validate_scheduler_tick,
)
from .scope_ports import FunctionalScopePort, GovScopePort
from .signing import DemoDigestSigner, DemoDigestVerifier, SignatureEnvelope, SigningPolicy, TrustPolicy, VerificationResult, demo_sign_and_verify
from .state_index import ArtifactStateIndex
from .state_machine import (
    GovRunState,
    StateTransition,
    apply_state_transition,
    validate_run_state,
    validate_state_transition,
)
from .state_store import GovStateStore
from .surfaces import (
    GovSurface,
    admission_policy_surface,
    domain_profile_sdk_surface,
    public_surface_index,
    runtime_contract_proofs_surface,
)

__all__ = [
    'CapabilityDeclaration',
    'CommandResult',
    'BoundaryReport',
    'ControlDecision',
    'DomainProfile',
    'DomainProfileConformance',
    'DomainProfileContract',
    'EvidenceRuleDeclaration',
    'GovAdmissionDecision',
    'GovApiError',
    'GovApiResult',
    'GovApprovalRequest',
    'GovAuditRecord',
    'GovEngineContext',
    'GovEnginePaths',
    'GovEvidenceClaim',
    'GovEvidenceQualification',
    'GovEvidenceRequirement',
    'GovControlAction',
    'GovernanceVocabularyEntry',
    'ArtifactChangeOrder',
    'ArtifactConflict',
    'ArtifactDescriptor',
    'ArtifactEnvelope',
    'ArtifactLifecycleController',
    'ArtifactState',
    'ArtifactStateIndex',
    'ConflictDetector',
    'ExecutionGate',
    'ExecutionGateInput',
    'ExecutionPrerequisites',
    'EventEnvelope',
    'DryRunRunner',
    'DemoDigestSigner',
    'DemoDigestVerifier',
    'GovernanceContext',
    'GovExecutionBackend',
    'GovEvent',
    'GovObservation',
    'GovOodaController',
    'GovOodaDecision',
    'GovOrientation',
    'GovPlanIntentContract',
    'GovPolicyDecision',
    'GovQueueLane',
    'GovQueueSnapshot',
    'GovReviewResult',
    'GovRoleAdapters',
    'GovRunnerLease',
    'GovRunState',
    'GovRuntimeSnapshot',
    'GovSchedulerTick',
    'RuntimeAdmissionResult',
    'GuardedBundleRuntimeDecision',
    'GuardReplayDecision',
    'GuardReplayRecord',
    'GovSurface',
    'GovSupervisionDecision',
    'GovSupervisionPlan',
    'GovTaskContract',
    'KernelBoundary',
    'OrchestrationStep',
    'OrchestratorBoundary',
    'PlanningStageRegistry',
    'PlannerPort',
    'PolicyHookDeclaration',
    'ProfileConformanceReport',
    'ResourceTypeRegistry',
    'RuntimeContractProof',
    'RunnerProfileDeclaration',
    'TaskFamilyRegistry',
    'FunctionalScopePort',
    'ReasonCode',
    'RunnerProfile',
    'GovScopePort',
    'SignatureEnvelope',
    'SigningPolicy',
    'StateTransition',
    'GovSCLiteLifecycleVerifier',
    'GovStateStore',
    'review_bundle_state',
    'review_bundle_transition_decision',
    'review_sclite_bundle',
    'TransitionDecision',
    'TransitionGate',
    'TransitionPolicy',
    'TrustPolicy',
    'VerificationResult',
    'admission_decision_from_host_gate',
    'admission_policy_surface',
    'apply_control_decision',
    'compose_runtime_admission_result',
    'control_action_from_host_action',
    'demo_sign_and_verify',
    'apply_state_transition',
    'boundary_surface_index',
    'domain_profile_conformance',
    'domain_profile_sdk_surface',
    'evaluate_guard_replay',
    'governance_contract_vocabulary',
    'guard_replay_record_from_guard',
    'host_compat_context',
    'kernel_boundary_contract',
    'kernel_boundary_report',
    'known_profile_contracts',
    'orchestrator_boundary_contract',
    'public_surface_index',
    'qualify_evidence_claim',
    'queue_snapshot_from_lanes',
    'ravenclaw_context',
    'ravenclaw_contract_proof',
    'ravenclaw_profile_contract',
    'ravenclaw_security_profile',
    'record_guard_replay',
    'record_guard_replay_file',
    'verify_guard_and_record_replay',
    'runner_lease_from_request',
    'runtime_contract_proofs_surface',
    'supervision_plan_from_runner_request',
    'tecrax_contract_proof',
    'tecrax_infra_ops_profile',
    'validate_admission_decision',
    'validate_approval_request',
    'validate_audit_record',
    'validate_domain_profile',
    'validate_domain_profile_contract',
    'validate_domain_profile_conformance',
    'validate_control_decision',
    'validate_control_action',
    'validate_evidence_claim',
    'validate_evidence_qualification',
    'validate_evidence_requirement',
    'validate_event_envelope',
    'validate_gov_event',
    'validate_governance_contract_vocabulary',
    'validate_orchestration_step',
    'task_contract_from_host_task',
    'validate_plan_intent_contract',
    'validate_planner_port',
    'validate_profile_conformance',
    'validate_policy_decision',
    'validate_queue_snapshot',
    'validate_runner_lease',
    'validate_runner_receipt_for_request',
    'validate_run_state',
    'validate_review_result',
    'validate_runtime_snapshot',
    'validate_runtime_contract_proof',
    'validate_scheduler_tick',
    'validate_runtime_admission_result',
    'validate_state_transition',
    'validate_supervised_runner_request',
    'validate_supervision_decision',
    'validate_supervision_plan',
    'validate_task_contract',
    'verify_lifecycle_manifest',
    'profile_conformance_report',
]


def __getattr__(name: str):
    if name in {
        'GovSCLiteLifecycleVerifier',
        'review_bundle_state',
        'review_bundle_transition_decision',
        'review_sclite_bundle',
        'verify_lifecycle_manifest',
    }:
        from .sclite_contracts import (
            GovSCLiteLifecycleVerifier,
            review_bundle_state,
            review_bundle_transition_decision,
            review_sclite_bundle,
            verify_lifecycle_manifest,
        )

        return {
            'GovSCLiteLifecycleVerifier': GovSCLiteLifecycleVerifier,
            'review_bundle_state': review_bundle_state,
            'review_bundle_transition_decision': review_bundle_transition_decision,
            'review_sclite_bundle': review_sclite_bundle,
            'verify_lifecycle_manifest': verify_lifecycle_manifest,
        }[name]
    raise AttributeError(name)
